DROP TABLE IF EXISTS flyway_schema_history;
DROP TABLE IF EXISTS departments cascade;
DROP TABLE IF EXISTS employees cascade;

create table departments (
    id bigint generated by default as identity,
    department_description varchar(255),
    department_name varchar(255),
    primary key (id));

create table employees (
    id bigint generated by default as identity,
    email_id varchar(255) not null unique,
    first_name varchar(255),
    last_name varchar(255),
    department_id bigint,
    primary key (id));

alter table if exists employees add constraint dept_key foreign key (department_id) references departments;



