-- UserInfo 테스트 계정은 Flyway SQL에 BCrypt 해시를 하드코딩하지 않습니다.
-- BCrypt는 생성 시 랜덤 Salt가 붙으므로 SQL에 미리 쓴 해시는 검증이 불가능합니다.
--
-- 대신 아래 두 가지 방법으로 계정을 삽입합니다.
--
-- [방법 1] 애플리케이션 기동 시 UserInfoInsertRunner 가 자동 실행 (prod 프로파일)
--          → runner/UserInfoInsertRunner.java 참고
--
-- [방법 2] 서버 기동 후 POST /userinfos/new API 직접 호출 (permitAll)
--          POST http://localhost:8080/userinfos/new
--          Content-Type: application/json
--          {"name":"Admin","email":"admin@company.com","password":"password","roles":"ROLE_ADMIN"}
